steps:
- checkout: self
  fetchDepth: 2

- script: |
    sudo apt install gdb
  displayName: Install GDB

- script: |
    pip install --user awscli
        
    curl -fo $HOME/stamp https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-03-17-stamp-x86_64-unknown-linux-musl
    chmod +x $HOME/stamp
    
    export PATH=$PATH:$HOME/.local/bin:$HOME/Library/Python/2.7/bin/:$HOME
    echo "##vso[task.setvariable variable=PATH;]$PATH"

    mkdir -p $HOME/rustsrc

    # TODO: fix
    echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]linux"
  displayName:  Prep

# TODO: comment out for now ... not sure Azure Pipelines has this problem
# FIXME(#46924): these two commands are required to enable IPv6,
# they shouldn't exist, please revert once more official solutions appeared.
# see https://github.com/travis-ci/travis-ci/issues/8891#issuecomment-353403729
#- script: |
#    echo '{"ipv6":true,"fixed-cidr-v6":"fd9a:8454:6789:13f7::/64"}' | sudo tee /etc/docker/daemon.json
#    sudo service docker restart
#  condition: and(succeeded(), eq(variables['Agent.OS'],'Linux'))
#  displayName: Enable IPv6
  
- template: show-disk-usage.yml

# TODO: Usng the job display name feels brittle. Is there a different varibale representing the current matrix entry name?
# TODO: should update the 2 scripts that look for TRAVIS_OS_NAME (look for AGENT_OS too)
- script: |
    echo "Job display name: $SYSTEM_JOBDISPLAYNAME"
    [ -z "$IMAGE" ] && export IMAGE=$SYSTEM_JOBDISPLAYNAME
    export RUN_SCRIPT="$BUILD_SOURCESDIRECTORY/src/ci/init_repo.sh . $HOME/rustsrc && src/ci/docker/run.sh $IMAGE"
    echo "$RUN_SCRIPT"
    echo "##vso[task.setvariable variable=IMAGE]$IMAGE"
    echo "##vso[task.setvariable variable=RUN_SCRIPT]$RUN_SCRIPT"
  displayName: Prepare run script

- script: printenv
  displayName: Dump env variables (look at IMAGE and RUN_SCRIPT.. and trailing single quote)

- script: |
    sudo sh -c 'echo "/checkout/obj/cores/core.%p.%E" > /proc/sys/kernel/core_pattern'
  displayName: Enable core dump

- template: verify-publish-toolstate.yml

# Log time information from this machine and an external machine for insight into possible
# clock drift. Timezones don't matter since relative deltas give all the necessary info.
# TODO: see travis.yml --- it does more
- script: |
    date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
  displayName: check for clock skew before

- template: run-script.yml

- script: |
    date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
  displayName: Check for clock skew after
