steps:
- checkout: self
  fetchDepth: 2

- template: show-environment-variables.yml
- template: show-disk-usage.yml

- bash: |
    sudo apt install gdb
        
    curl -fo $HOME/stamp https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-03-17-stamp-x86_64-unknown-linux-musl
    chmod +x $HOME/stamp
    
    export PATH=$PATH:$HOME/.local/bin:$HOME/Library/Python/2.7/bin/:$HOME
    echo "##vso[task.setvariable variable=PATH;]$PATH"

    mkdir -p $HOME/rustsrc

    # FIXME: update scripts to not depend on TRAVIS_OS_NAME
    echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]linux"
  displayName:  Prep

# FIXME: using the job display name feels brittle. Is there a better variable that represents the current matrix key?
- bash: |
    echo "Job display name: $SYSTEM_JOBDISPLAYNAME"
    [ -z "$IMAGE" ] && export IMAGE=$SYSTEM_JOBDISPLAYNAME
    export RUN_SCRIPT="$BUILD_SOURCESDIRECTORY/src/ci/init_repo.sh . $HOME/rustsrc && src/ci/docker/run.sh $IMAGE"    
    echo "##vso[task.setvariable variable=IMAGE]$IMAGE"
    echo "##vso[task.setvariable variable=RUN_SCRIPT]$RUN_SCRIPT"
  displayName: Prepare run script

- template: show-environment-variables.yml

- bash: sudo sh -c 'echo "/checkout/obj/cores/core.%p.%E" > /proc/sys/kernel/core_pattern'
  displayName: Enable core dump

- template: verify-publish-toolstate.yml

- template: run-script.yml
