steps:
- checkout: self
  fetchDepth: 2

- template: show-disk-usage.yml

- bash: |
    export PATH=$PATH:$HOME/.local/bin:$HOME/Library/Python/2.7/bin/
    mkdir -p $HOME/rustsrc    
    echo "##vso[task.setvariable variable=PATH;]$PATH"

    curl -fo /usr/local/bin/sccache https://rustlangtools.blob.core.windows.net/public/stable-x86_64-apple-darwin.sccache
    chmod +x /usr/local/bin/sccache

    curl -fo /usr/local/bin/stamp https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-03-17-stamp-x86_64-apple-darwin
    chmod +x /usr/local/bin/stamp
    
    curl -f http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz | tar xJf - 
    
    export CC=`pwd`/clang+llvm-7.0.0-x86_64-apple-darwin/bin/clang
    echo "##vso[task.setvariable variable=CC]$CC"
    
    export CXX=`pwd`/clang+llvm-7.0.0-x86_64-apple-darwin/bin/clang++
    echo "##vso[task.setvariable variable=CXX]$CXX"
    
    echo "##vso[task.setvariable variable=AR]$ar"

    # FIXME: fix
    echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]osx"
  displayName: Prep
  
- bash: |
    brew update
    brew install xz
    brew install swig
  condition: and(succeeded(), eq(variables['RUST_CHECK_TARGET'],'dist'))
  displayName: Install xz and swigw

- bash: |
    set -x
    export RUN_SCRIPT="$BUILD_SOURCESDIRECTORY/src/ci/init_repo.sh . $HOME/rustsrc && src/ci/run.sh && sccache --show-stats"
    echo "$RUN_SCRIPT"
    echo "##vso[task.setvariable variable=RUN_SCRIPT]$RUN_SCRIPT"
  displayName: Prepare run script

- template: show-environment-variables.yml

- template: verify-publish-toolstate.yml

- template: run-script.yml
