steps:
  # TODO: for whatever reason the value of RUN_SCRIPT ends with a single quote .. why? Should need this substituion logic
  # TODO: shouldn't need to set CI, TRavis, CI_JOB_NAME, etc here ... how is $IMAGE different from $CI_JOB_NAME?
  - script: |    
      echo RUN_SCRIPT="$RUN_SCRIPT"
      export RUN_SCRIPT="${RUN_SCRIPT//\'}"
      echo RUN_SCRIPT="$RUN_SCRIPT"

      echo TRAVIS_OS_NAME="$TRAVIS_OS_NAME"
      export TRAVIS_OS_NAME="${TRAVIS_OS_NAME//\'}"
      echo TRAVIS_OS_NAME="$TRAVIS_OS_NAME"

      echo IMAGE="$IMAGE"
      export IMAGE="${IMAGE//\'}"
      echo IMAGE="$IMAGE"

      #echo Emulate for CiEnv
      #export CI="true"
      #export TRAVIS="true"
      #

      export SCCACHE_AZURE_CONNECTION_STRING=$rustlangtools_CONNECTION_STRING
      export DOCKER_LAYER_CACHE_ACCOUNT_KEY=$rustlangtools_ACCOUNT_KEY

      if [ "$DISABLE_SCCACHE" == "1" ]; then unset SCCACHE_AZURE_CONNECTION_STRING; fi

      printenv | sort | grep -v SCCACHE_AZURE_CONNECTION_STRING
      printenv | sort | grep -v DOCKER_LAYER_CACHE_ACCOUNT_KEY
      which sccache
      stamp sh -x -c "$RUN_SCRIPT"
    displayName: Run script
    env:
      CI: true
      TRAVIS: true
      CI_JOB_NAME: $(System.JobDisplayName)
      TRAVIS_BRANCH: $(Build.SourceBranchName)

      # explicitly decrypt secret variables
      # see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
      rustlangtools_CONNECTION_STRING: $(rustlangtools_CONNECTION_STRING)
      rustlangtools_ACCOUNT_KEY: $(rustlangtools_ACCOUNT_KEY)
