steps:
# Log time information from this machine and an external machine for insight into possible
# clock drift. Timezones don't matter since relative deltas give all the necessary info.
- bash: |
    date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
  displayName: Log time information (before)

- bash: |    
    if [ "$DISABLE_SCCACHE" == "1" ]; then unset SCCACHE_AZURE_CONNECTION_STRING; fi
    which sccache
    stamp sh -x -c "$RUN_SCRIPT"
  env:
    CI: true
    CI_JOB_NAME: $(System.JobDisplayName)
    SRC: .
    NO_CCACHE: 1

    # Explicitly decrypt secret variables
    # See https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
    SCCACHE_AZURE_CONNECTION_STRING: $(SCCACHE_AZURE_CONNECTION_STRING_SECRET)
    DOCKER_LAYER_CACHE_AZURE_STORAGE_ACCOUNT_KEY: $(DOCKER_LAYER_CACHE_AZURE_STORAGE_ACCOUNT_KEY_SECRET)
  displayName: Run script

- bash: |
    date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
  displayName: Log time information (after)
