steps:
# TODO: for whatever reason the value of RUN_SCRIPT ends with a single quote .. why? Should need this substituion logic
# TODO: shouldn't need to set CI, TRavis, CI_JOB_NAME, etc here ... how is $IMAGE different from $CI_JOB_NAME?
- script: |    
    echo RUN_SCRIPT="$RUN_SCRIPT"
    export RUN_SCRIPT="${RUN_SCRIPT//\'}"
    echo RUN_SCRIPT="$RUN_SCRIPT"

    echo TRAVIS_OS_NAME="$TRAVIS_OS_NAME"
    export TRAVIS_OS_NAME="${TRAVIS_OS_NAME//\'}"
    echo TRAVIS_OS_NAME="$TRAVIS_OS_NAME"

    echo IMAGE="$IMAGE"
    export IMAGE="${IMAGE//\'}"
    echo IMAGE="$IMAGE"
  
    if [ "$DISABLE_SCCACHE" == "1" ]; then unset SCCACHE_AZURE_CONNECTION_STRING; fi

    printenv | sort
    which sccache
    
    stamp sh -x -c "$RUN_SCRIPT"
  env:
    CI: true
    TRAVIS: true # TODO
    CI_JOB_NAME: $(System.JobDisplayName)
    TRAVIS_BRANCH: $(Build.SourceBranchName)

    # explicitly decrypt secret variables
    # see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
    SCCACHE_AZURE_CONNECTION_STRING: $(SCCACHE_AZURE_CONNECTION_STRING_SECRET)
    DOCKER_LAYER_CACHE_AZURE_STORAGE_ACCOUNT_KEY: $(DOCKER_LAYER_CACHE_AZURE_STORAGE_ACCOUNT_KEY_SECRET)
  displayName: Run script
