#
# Azure Pipelines pull request build for Rust
# 

trigger: none
pr:
- master # TODO: really just want any branch, but want an explicit "pr" property set so it's clear

variables:
  # By default schannel checks revocation of certificates unlike some other SSL
  # backends, but we've historically had problems on CI where a revocation
  # server goes down presumably. See #43333 for more info
  CARGO_HTTP_CHECK_REVOKE: false
  
  # for sccache (requires the SCCACHE_AZURE_CONNECTION_STRING_SECRET secret variable to be set)
  SCCACHE_AZURE_BLOB_CONTAINER: rust-sccache

  # for docker caching (also requires the DOCKER_LAYER_CACHE_AZURE_STORAGE_ACCOUNT_KEY_SECRET secret variable to be set)
  DOCKER_LAYER_CACHE_AZURE_STORAGE_ACCOUNT: rustlangtools
  DOCKER_LAYER_CACHE_AZURE_STORAGE_CONTAINER: rust-docker

jobs:
- job: Linux
  timeoutInMinutes: 600
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: steps/linux.yml
  strategy:
    matrix:
      x86_64-gnu-llvm-6.0:
        RUST_BACKTRACE: 1

      x86_64-gnu-tools:
        DEPLOY: 0
      # if: branch = auto OR (type = pull_request AND commit_message =~ /(?i:^update.*\b(rls|rustfmt|clippy|miri|cargo)\b)/)

      mingw-check:
        DEPLOY: 0
