#
# Azure Pipelines "try" branch build for Rust
# 

variables:
  # By default schannel checks revocation of certificates unlike some other SSL
  # backends, but we've historically had problems on CI where a revocation
  # server goes down presumably. See #43333 for more info
  CARGO_HTTP_CHECK_REVOKE: false
  
  # for sccache (requires the SCCACHE_AZURE_CONNECTION_STRING_SECRET secret variable to be set)
  SCCACHE_AZURE_BLOB_CONTAINER: rust-sccache

  # for docker caching (also requires the DOCKER_LAYER_CACHE_AZURE_STORAGE_ACCOUNT_KEY_SECRET secret variable to be set)
  DOCKER_LAYER_CACHE_AZURE_STORAGE_ACCOUNT: rustlangtools
  DOCKER_LAYER_CACHE_AZURE_STORAGE_CONTAINER: rust-docker

pr: none
trigger:
- try

jobs:
- job: Linux
  timeoutInMinutes: 300
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      dist-x86_64-linux:
        DEPLOY: 1

      # "alternate" deployments, these are "nightlies" but have LLVM assertions
      # turned on, they're deployed to a different location primarily for
      # additional testing.
      dist-x86_64-linux-alt:
        IMAGE: dist-x86_64-linux
        DEPLOY_ALT: 1
  steps:
  - template: steps/linux.yml
